on:
  push:
    branches:
      - test

jobs:
  generate_index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Fasdr index and commit .embeddings folder
        uses: dmarx/fasdr-action@v1.0.3
        with:
          path-to-index: ./fast-and-simple-dense-retrieval
